Expose Java client metrics via factory from ClientId
evolution-gaming/skafka pull request #433
Opened 2024-07-21 09:46 UTC by dfakhritdinov

Make Java client metrics usable with `ProducerMetrics.of` & `ConsumerMetrics.Of` factories

2024-07-23 20:02 UTC, stasimus requested changes

2024-07-24 10:11 UTC, dfakhritdinov commented on modules/metrics/src/main/scala/com/evolutiongaming/skafka/consumer/ConsumerMetricsOf.scala
> +      new ConsumerMetrics[F] {
Thanks for the suggestion. Extracted into `consumerMetricsOf` method

2024-07-24 10:11 UTC, dfakhritdinov commented on modules/metrics/src/main/scala/com/evolutiongaming/skafka/producer/ProducerMetricsOf.scala
> +      new ProducerMetrics[F] {
Thanks for the suggestion. Extracted into `producerMetricsOf` method

2024-07-24 12:32 UTC, stasimus approved these changes

2024-07-24 12:51 UTC, merged